name: Node.js Docker CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Cache Docker layers
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ hashFiles('**/Dockerfile') }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t my-node-app .
          docker images  # List Docker images to verify the build

      # Log in to Docker Hub (use your Docker Hub username and access token)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Push Docker image to Docker Hub (or another registry if you use that)
      - name: Push Docker image
        run: |
          docker images  # List Docker images to verify the build
          docker tag my-node-app:latest ${{ secrets.DOCKER_USERNAME }}/my-node-app:${{ github.sha }}
          docker tag my-node-app:latest ${{ secrets.DOCKER_USERNAME }}/my-node-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/my-node-app:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/my-node-app:latest

